# Generated by Django 5.0.1 on 2024-02-06 01:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("BookApp", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Languages",
            new_name="Language",
        ),
    ]
